### ISSUE TITLE
Small issue with C++ generated code

### ISSUE THREAD

**Issue by danichcr72** [opengql/grammar#15]
Hi,

  Thank you very much for putting this out to the open source community!

  There's a small issue with the keywords NULL and INFINITY that crops up when generating a C++ parser.  Those keywords correspond to common preprocessor macros in the language.  It might be possible to make a small change to the grammar to overcome this.  The diff is as follows:

1916c1916
<     : NULL
---
>     : NULLK
1920c1920
<     : NULL notNull
---
>     : NULLK notNull
1994c1994
<     :  NOT NULL
---
>     :  NOT NULLK
2054c2054
<     : IS NOT? NULL
---
>     : IS NOT? NULLK
3016c3016
<     : NULL
---
>     : NULLK
3414c3414
< NULL: 'NULL';
---
> NULLK: 'NULL';
3519c3519
< INFINITY: 'INFINITY';
---
> INFINITYK: 'INFINITY';

I'll be happy to put up a pull request if it's preferable.

Thanks,

Daniel Ch.

**Comment by mburbidg** [comment]
Thanks. I fixed the issue.
