### ISSUE TITLE
Another C++ macro clash

### ISSUE THREAD

**Issue by danichcr72** [opengql/grammar#19]
The LOG symbol name clashes with a macro used commonly in C++.  Here are some possible changes to the grammar:

 generalLogarithmFunction
-    : LOG LEFT_PAREN generalLogarithmBase COMMA generalLogarithmArgument RIGHT_PAREN
+    : LOGFN LEFT_PAREN generalLogarithmBase COMMA generalLogarithmArgument RIGHT_PAREN

-LOG: 'LOG';
+LOGFN: 'LOG';

Thanks for your kind attention and help.

**Comment by mburbidg** [comment]
Renamed LOG to LOGKW.
