### ISSUE TITLE
Possible operator precedence problems with AND

### ISSUE THREAD

**Issue by danichcr72** [opengql/grammar#20]
Hi,

  I have observed that the AND operator appears to be binding at a higher precedence than it should.  The following example requires the parentheses to indicate the right binding:

```
MATCH (a)-[b]->(c)
WHERE (a.id > 0) AND (b.other = TRUE)
RETURN a.id + 1, b.dat + 'mystr', c.id - 0.5
````

When the parentheses are removed `WHERE a.id > 0 AND b.other = TRUE` then the and appears to bind to 0 on the left side and b.other on the right side.

Is this an issue or am I misinterpreting something here?

Thanks,

Daniel Ch.

**Comment by danichcr72** [comment]
Thanks for the responsiveness!

**Comment by mburbidg** [comment]
Fixed the precedence bug. Also simplified boolean predicates somewhat.
